### ISSUE TITLE
Error ICH prediction

### ISSUE THREAD

**Issue by smcch** [msharrock/deepbleed#13]
Hi, After following the instructions I got an error when I run the script:

op/deepbleed/output --weights /Users/Santi-Anuky/Desktop/deepbleed/weights 
2022-02-12 17:15:05.788469: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-12 17:15:05.901410: W tensorflow/core/util/tensor_slice_reader.cc:96] Could not open /Users/Santi-Anuky/Desktop/deepbleed/weights: FAILED_PRECONDITION: /Users/Santi-Anuky/Desktop/deepbleed/weights; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "predict.py", line 56, in <module>
    model.load_weights(WEIGHT_PATH)
  File "/Users/Santi-Anuky/opt/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/Santi-Anuky/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 2593, in load_weights
    raise ValueError(

ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.

Python 3.9
OS: Mac OS Catalina 10.15.5
PyCharm

Could you please help me?

**Comment by msharrock** [comment]
Hi, sorry I didn't see this earlier. Are you using the docker image? What version of tensorflow are you using?

**Comment by smcch** [comment]
Hi, I'm not using docker. Tensorflow 2.8.0

**Comment by msharrock** [comment]
The readme states that the version to use is Tensorflow 2.2.  The reason I use a docker container is that it has all the pre-requisite programs already there.
